import type { Metadata } from "next";
import Script from "next/script"; // ✅ Import Script from Next
import "./globals.css";

export const metadata: Metadata = {
	title: "Webally",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="/favicon.svg"
				/>
			</head>

			{/* ✅ Google Analytics Script */}
			<Script
				src="https://www.googletagmanager.com/gtag/js?id=G-3K4T87S1HQ"
				strategy="afterInteractive"
			/>
			<Script
				id="google-analytics"
				strategy="afterInteractive">
				{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-3K4T87S1HQ');
        `}
			</Script>

			<body className="antialiased">{children}</body>
		</html>
	);
}
